"""Add edited sections to extraction

Revision ID: 32157f36cd15
Revises: 0e535899dfa4
Create Date: 2025-12-05 06:42:20.988716+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32157f36cd15'
down_revision: Union[str, None] = '0e535899dfa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_extractions', sa.Column('edited_sections', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinical_extractions', 'edited_sections')
    # ### end Alembic commands ###
