"""Add decision model and review tracking

Revision ID: 0e535899dfa4
Revises: 1c5eeb81cbb8
Create Date: 2025-12-05 06:35:50.176294+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e535899dfa4'
down_revision: Union[str, None] = '1c5eeb81cbb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('decision_type', sa.Enum('APPROVED', 'DENIED', 'PENDING', 'NEEDS_CLARIFICATION', name='decisiontype'), nullable=False),
    sa.Column('sub_status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.String(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_decisions_id'), 'decisions', ['id'], unique=False)
    op.add_column('cases', sa.Column('is_reviewed', sa.Boolean(), nullable=True))
    op.add_column('cases', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('cases', sa.Column('reviewed_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'reviewed_by')
    op.drop_column('cases', 'reviewed_at')
    op.drop_column('cases', 'is_reviewed')
    op.drop_index(op.f('ix_decisions_id'), table_name='decisions')
    op.drop_table('decisions')
    # ### end Alembic commands ###
