"""optimize_indexes_and_performance

Revision ID: f8992c27166a
Revises: f7a8b9c0d1e2
Create Date: 2026-01-30 06:11:59.312989+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8992c27166a'
down_revision: Union[str, None] = 'f7a8b9c0d1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # -----------------------------------------------------------
    # DATA CLEANUP: Remove orphaned records before adding constraints
    # This prevents IntegrityError on existing dirty data
    # -----------------------------------------------------------
    op.execute("DELETE FROM entity_sources WHERE user_id NOT IN (SELECT id FROM users)")

    op.drop_index('idx_case_files_user_case', table_name='case_files')
    op.drop_index('idx_case_files_user_id', table_name='case_files')
    op.create_index('idx_case_file_case_order', 'case_files', ['case_id', 'file_order'], unique=False)
    op.create_index(op.f('ix_case_files_user_id'), 'case_files', ['user_id'], unique=False)
    op.alter_column('case_notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('idx_case_notes_user_id', table_name='case_notes')
    op.create_index(op.f('ix_case_notes_user_id'), 'case_notes', ['user_id'], unique=False)
    op.alter_column('cases', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('cases', 'processed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('cases', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('idx_cases_user_case_number', table_name='cases')
    op.drop_index('idx_cases_user_id', table_name='cases')
    op.create_index('idx_case_case_number_user', 'cases', ['case_number', 'user_id'], unique=False)
    op.create_index('idx_case_status_created', 'cases', ['status', 'uploaded_at'], unique=False)
    op.create_index('idx_case_user_status', 'cases', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_cases_uploaded_at'), 'cases', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_cases_user_id'), 'cases', ['user_id'], unique=False)
    op.drop_index('idx_clinical_extractions_user_id', table_name='clinical_extractions')
    op.create_index('idx_extraction_case_user', 'clinical_extractions', ['case_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_clinical_extractions_user_id'), 'clinical_extractions', ['user_id'], unique=False)
    op.drop_constraint('conversation_messages_user_id_fkey', 'conversation_messages', type_='foreignkey')
    op.drop_constraint('conversation_messages_case_id_fkey', 'conversation_messages', type_='foreignkey')
    op.drop_index('idx_dashboard_snapshots_user_id', table_name='dashboard_snapshots')
    op.create_index('idx_snapshot_case_created', 'dashboard_snapshots', ['case_id', 'created_at'], unique=False)
    op.create_index('idx_snapshot_case_user', 'dashboard_snapshots', ['case_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_dashboard_snapshots_id'), 'dashboard_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_dashboard_snapshots_user_id'), 'dashboard_snapshots', ['user_id'], unique=False)
    op.create_foreign_key(None, 'dashboard_snapshots', 'cases', ['case_id'], ['id'])
    op.alter_column('decisions', 'decided_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('decisions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('idx_decisions_user_id', table_name='decisions')
    op.create_index(op.f('ix_decisions_user_id'), 'decisions', ['user_id'], unique=False)
    op.alter_column('document_chunks', 'bbox',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('idx_document_chunks_user_id', table_name='document_chunks')
    op.drop_index('idx_embedding_cosine', table_name='document_chunks', postgresql_using='hnsw')
    op.create_index('idx_chunk_case_section', 'document_chunks', ['case_id', 'section_type'], unique=False)
    op.create_index('idx_chunk_file_page', 'document_chunks', ['file_id', 'page_number'], unique=False)
    op.create_index(op.f('ix_document_chunks_user_id'), 'document_chunks', ['user_id'], unique=False)
    op.drop_index('ix_entity_sources_entity', table_name='entity_sources')
    op.drop_constraint('uq_entity_source', 'entity_sources', type_='unique')
    op.create_index(op.f('ix_entity_sources_entity_type'), 'entity_sources', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entity_sources_id'), 'entity_sources', ['id'], unique=False)
    op.create_foreign_key(None, 'entity_sources', 'document_chunks', ['chunk_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'entity_sources', 'cases', ['case_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'entity_sources', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'entity_sources', 'case_files', ['file_id'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_case_clicked', table_name='evidence_clicks')
    op.drop_index('idx_user_case_clicked', table_name='evidence_clicks')
    op.drop_index('idx_user_clicked', table_name='evidence_clicks')
    op.drop_index('idx_user_entity_type', table_name='evidence_clicks')
    op.drop_index('ix_evidence_clicks_clicked_at', table_name='evidence_clicks')
    op.create_index('idx_click_case_user', 'evidence_clicks', ['case_id', 'user_id'], unique=False)
    op.create_index('idx_click_user_created', 'evidence_clicks', ['user_id', 'clicked_at'], unique=False)
    op.drop_index('idx_facet_results_user_id', table_name='facet_results')
    op.create_index('idx_facet_snapshot_type', 'facet_results', ['snapshot_id', 'facet_type'], unique=False)
    op.create_index(op.f('ix_facet_results_id'), 'facet_results', ['id'], unique=False)
    op.create_index(op.f('ix_facet_results_user_id'), 'facet_results', ['user_id'], unique=False)
    op.create_foreign_key(None, 'facet_results', 'cases', ['case_id'], ['id'])
    op.create_index(op.f('ix_source_links_id'), 'source_links', ['id'], unique=False)
    op.create_foreign_key(None, 'source_links', 'cases', ['case_id'], ['id'])
    op.create_index('idx_usage_metadata', 'usage_metrics', ['extra_metadata'], unique=False, postgresql_using='gin')
    op.alter_column('user_preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('user_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint('wallets_user_id_key', 'wallets', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('wallets_user_id_key', 'wallets', ['user_id'])
    op.alter_column('users', 'last_login',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('user_preferences', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('user_preferences', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index('idx_usage_metadata', table_name='usage_metrics', postgresql_using='gin')
    op.drop_constraint(None, 'source_links', type_='foreignkey')
    op.drop_index(op.f('ix_source_links_id'), table_name='source_links')
    op.drop_constraint(None, 'facet_results', type_='foreignkey')
    op.drop_index(op.f('ix_facet_results_user_id'), table_name='facet_results')
    op.drop_index(op.f('ix_facet_results_id'), table_name='facet_results')
    op.drop_index('idx_facet_snapshot_type', table_name='facet_results')
    op.create_index('idx_facet_results_user_id', 'facet_results', ['user_id'], unique=False)
    op.drop_index('idx_click_user_created', table_name='evidence_clicks')
    op.drop_index('idx_click_case_user', table_name='evidence_clicks')
    op.create_index('ix_evidence_clicks_clicked_at', 'evidence_clicks', ['clicked_at'], unique=False)
    op.create_index('idx_user_entity_type', 'evidence_clicks', ['user_id', 'entity_type', 'clicked_at'], unique=False)
    op.create_index('idx_user_clicked', 'evidence_clicks', ['user_id', 'clicked_at'], unique=False)
    op.create_index('idx_user_case_clicked', 'evidence_clicks', ['user_id', 'case_id', 'clicked_at'], unique=False)
    op.create_index('idx_case_clicked', 'evidence_clicks', ['case_id', 'clicked_at'], unique=False)
    op.drop_constraint(None, 'entity_sources', type_='foreignkey')
    op.drop_constraint(None, 'entity_sources', type_='foreignkey')
    op.drop_constraint(None, 'entity_sources', type_='foreignkey')
    op.drop_constraint(None, 'entity_sources', type_='foreignkey')
    op.drop_index(op.f('ix_entity_sources_id'), table_name='entity_sources')
    op.drop_index(op.f('ix_entity_sources_entity_type'), table_name='entity_sources')
    op.create_unique_constraint('uq_entity_source', 'entity_sources', ['case_id', 'entity_type', 'entity_id'])
    op.create_index('ix_entity_sources_entity', 'entity_sources', ['entity_type', 'entity_id'], unique=False)
    op.drop_index(op.f('ix_document_chunks_user_id'), table_name='document_chunks')
    op.drop_index('idx_chunk_file_page', table_name='document_chunks')
    op.drop_index('idx_chunk_case_section', table_name='document_chunks')
    op.create_index('idx_embedding_cosine', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw')
    op.create_index('idx_document_chunks_user_id', 'document_chunks', ['user_id'], unique=False)
    op.alter_column('document_chunks', 'bbox',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_decisions_user_id'), table_name='decisions')
    op.create_index('idx_decisions_user_id', 'decisions', ['user_id'], unique=False)
    op.alter_column('decisions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('decisions', 'decided_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'dashboard_snapshots', type_='foreignkey')
    op.drop_index(op.f('ix_dashboard_snapshots_user_id'), table_name='dashboard_snapshots')
    op.drop_index(op.f('ix_dashboard_snapshots_id'), table_name='dashboard_snapshots')
    op.drop_index('idx_snapshot_case_user', table_name='dashboard_snapshots')
    op.drop_index('idx_snapshot_case_created', table_name='dashboard_snapshots')
    op.create_index('idx_dashboard_snapshots_user_id', 'dashboard_snapshots', ['user_id'], unique=False)
    op.create_foreign_key('conversation_messages_case_id_fkey', 'conversation_messages', 'cases', ['case_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('conversation_messages_user_id_fkey', 'conversation_messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_clinical_extractions_user_id'), table_name='clinical_extractions')
    op.drop_index('idx_extraction_case_user', table_name='clinical_extractions')
    op.create_index('idx_clinical_extractions_user_id', 'clinical_extractions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_cases_user_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_uploaded_at'), table_name='cases')
    op.drop_index('idx_case_user_status', table_name='cases')
    op.drop_index('idx_case_status_created', table_name='cases')
    op.drop_index('idx_case_case_number_user', table_name='cases')
    op.create_index('idx_cases_user_id', 'cases', ['user_id'], unique=False)
    op.create_index('idx_cases_user_case_number', 'cases', ['user_id', 'case_number'], unique=False)
    op.alter_column('cases', 'reviewed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('cases', 'processed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('cases', 'uploaded_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_case_notes_user_id'), table_name='case_notes')
    op.create_index('idx_case_notes_user_id', 'case_notes', ['user_id'], unique=False)
    op.alter_column('case_notes', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_case_files_user_id'), table_name='case_files')
    op.drop_index('idx_case_file_case_order', table_name='case_files')
    op.create_index('idx_case_files_user_id', 'case_files', ['user_id'], unique=False)
    op.create_index('idx_case_files_user_case', 'case_files', ['user_id', 'case_id'], unique=False)
    # ### end Alembic commands ###
