"""Add privacy_vault table for two-tier de-identification

Revision ID: b2257e8a37ea
Revises: b1c2d3e4f5a6
Create Date: 2026-02-10 10:45:15.741939+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2257e8a37ea'
down_revision: Union[str, None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('privacy_vault',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date_shift_days', sa.Integer(), nullable=False),
    sa.Column('token_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('shifted_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_privacy_vault_case', 'privacy_vault', ['case_id'], unique=False)
    op.create_index('idx_privacy_vault_expires', 'privacy_vault', ['expires_at'], unique=False)
    op.create_index('idx_privacy_vault_user', 'privacy_vault', ['user_id'], unique=False)
    op.create_index(op.f('ix_privacy_vault_case_id'), 'privacy_vault', ['case_id'], unique=False)
    op.create_index(op.f('ix_privacy_vault_user_id'), 'privacy_vault', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_privacy_vault_user_id'), table_name='privacy_vault')
    op.drop_index(op.f('ix_privacy_vault_case_id'), table_name='privacy_vault')
    op.drop_index('idx_privacy_vault_user', table_name='privacy_vault')
    op.drop_index('idx_privacy_vault_expires', table_name='privacy_vault')
    op.drop_index('idx_privacy_vault_case', table_name='privacy_vault')
    op.drop_table('privacy_vault')
    # ### end Alembic commands ###
