"""update_user_roles_upper_case

Revision ID: a030f3bad946
Revises: 5d09e3e397ca
Create Date: 2026-02-05 10:55:24.123385+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a030f3bad946'
down_revision: Union[str, None] = '5d09e3e397ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
